version: "3.8"

services:
    api:
        image: api:1.0
        build:
            context: ./backend/api
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: api
        ports:
            - 8081:8081
        volumes:
            - data:/app/data
    vue:
        image: vue:1.0
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: vue
        ports:
            - 8080:8080
        volumes:
            - data:/app/data